# ============================================
# Lesson 7 - Type Hints & Dataclasses
# ============================================

from dataclasses import dataclass, field
# dataclass  → decorator that auto generates __init__ and __repr__
# field      → used for complex default values like lists

from typing import List, Optional
# List[str]     → list of strings
# Optional[str] → value can be string OR None

# @dataclass automatically generates:
# 1. __init__ method
# 2. __repr__ method
# No need to write them manually!

@dataclass
class Project:
    # Required fields — must provide when creating object
    name: str               # project name — must be string
    status: str             # project status — must be string
    priority: str           # project priority — must be string

    # Optional fields — have default values
    tasks: List[str] = field(default_factory=list)
    # field(default_factory=list) → creates a NEW empty list for EACH object
    # Why not tasks: List[str] = [] → all objects would share ONE list! 😱

    description: Optional[str] = None
    # Optional[str] → value can be string OR None
    # Default is None — description not required!

    def add_task(self, task: str) -> None:
        # -> None means this method returns nothing
        # task: str means task parameter must be string
        self.tasks.append(task)
        print(f"Task '{task}' added to project '{self.name}'")

    def is_active(self) -> bool:
        # -> bool means this method returns True or False
        return self.status == "active"
        # if status IS "active"  → True
        # if status NOT "active" → False


# ============================================
# Testing
# ============================================

# Create project 1 — with description
project1 = Project(
    name="Task Manager",
    status="active",
    priority="high",
    description="A CLI based task management tool"
)

# Create project 2 — without description (None by default)
project2 = Project(
    name="Portfolio Website",
    status="on_hold",
    priority="medium"
)

# Print both projects — __repr__ auto generated by @dataclass!
print(project1)
# Expected Output:
# Project(name='Task Manager', status='active', priority='high', tasks=[], description='A CLI based task management tool')

print(project2)
# Expected Output:
# Project(name='Portfolio Website', status='on_hold', priority='medium', tasks=[], description=None)

print()

# Add tasks to project1
project1.add_task("Build Login")
# Expected Output: Task 'Build Login' added to project 'Task Manager'

project1.add_task("Build Dashboard")
# Expected Output: Task 'Build Dashboard' added to project 'Task Manager'

project1.add_task("Write Tests")
# Expected Output: Task 'Write Tests' added to project 'Task Manager'

print(f"Project 1 tasks: {project1.tasks}")
# Expected Output: Project 1 tasks: ['Build Login', 'Build Dashboard', 'Write Tests']

print()

# Check if projects are active
print(f"Is project1 active? {project1.is_active()}")
# Expected Output: Is project1 active? True

print(f"Is project2 active? {project2.is_active()}")
# Expected Output: Is project2 active? False

print()

# Prove each project has its OWN list — not shared!
project2.add_task("Design Homepage")
# Expected Output: Task 'Design Homepage' added to project 'Portfolio Website'

print(f"Project 1 tasks: {project1.tasks}")
# Expected Output: Project 1 tasks: ['Build Login', 'Build Dashboard', 'Write Tests']

print(f"Project 2 tasks: {project2.tasks}")
# Expected Output: Project 2 tasks: ['Design Homepage']