# ============================================
# Lesson 7 - Type Hints & Dataclasses Exercise
# ============================================

from dataclasses import dataclass, field
# dataclass  → decorator that auto generates __init__ and __repr__
# field      → used for complex default values like lists

from typing import List, Optional
# List[str]     → list of strings
# Optional[str] → value can be string OR None


@dataclass
class Task:
    # Required fields — must provide when creating object
    name: str                                       # task name — must be string
    status: str                                     # task status — must be string
    priority: str                                   # task priority — must be string

    # Optional fields — have default values
    tags: List[str] = field(default_factory=list)
    # field(default_factory=list) → creates NEW empty list for EACH object
    # Why not tags: List[str] = [] → all objects share ONE list! 😱

    description: Optional[str] = None
    # Optional[str] → value can be string OR None
    # Default is None — description not required!

    def mark_complete(self) -> None:
        # -> None means this method returns nothing
        self.status = "completed"
        print(f"Task '{self.name}' is completed!")

    def is_high_priority(self) -> bool:
        # -> bool means returns True or False
        # Cleaner way — comparison itself returns True/False!
        return self.priority == "high"


# ============================================
# Testing
# ============================================

# Create task1 — with tags and description
task1 = Task(
    name="Build Login",
    status="todo",
    priority="high",
    tags=["backend", "frontend"],
    description="Build the login page"
)

# Create task2 — no tags, no description (defaults used)
task2 = Task(
    name="Fix Bug",
    status="todo",
    priority="low"
    # tags → [] by default
    # description → None by default
)

# Print both tasks — __repr__ auto generated by @dataclass!
print(task1)
# Expected: Task(name='Build Login', status='todo', priority='high', tags=['backend', 'frontend'], description='Build the login page')

print(task2)
# Expected: Task(name='Fix Bug', status='todo', priority='low', tags=[], description=None)

print()

# Mark task1 complete
task1.mark_complete()
# Expected: Task 'Build Login' is completed!

print()

# Check high priority
print(f"Is task1 high priority? {task1.is_high_priority()}")
# Expected: Is task1 high priority? True

print(f"Is task2 high priority? {task2.is_high_priority()}")
# Expected: Is task2 high priority? False

print()

# Add tags to task2 separately
task2.tags.append("urgent")
task2.tags.append("backend")

# Prove tags are NOT shared between objects!
print(f"Task1 tags: {task1.tags}")
# Expected: Task1 tags: ['backend', 'frontend'] — unchanged!

print(f"Task2 tags: {task2.tags}")
# Expected: Task2 tags: ['urgent', 'backend'] — only task2's tags!